version: '3.4'

services:
  sqlserver:
    container_name: sqlserver.db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - '1433:1433'
    volumes:
      - sqlserver-data:/var/lib/sqlserver/data
    networks:
      - knowledge-base
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Admin@123$$

networks:
  knowledge-base:
    driver: bridge
volumes:
  sqlserver-data: